vscode:
  extensions:
    - rocketseat.RocketseatReactJS@2.2.0:CMZI2JF+9mcg15CoJkRPOQ==
    - PKief.material-icon-theme@3.9.3:GVmljEI1+vB8Qkqq/e1dfw==
    - wix.vscode-import-cost@2.12.0:Z31eYgMsqJCLYkcg0s66Ug==